spring:
  profiles:
    active:
      - prod
      - datajpa
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    defer-datasource-initialization: true
---
spring:
  config:
    activate:
      on-profile:
        - prod
        - uat
        - dev
prod:
  username: YmlProdUserName
  password: YmlProdPassword
  jdbcurl: YmlProdUrl